version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      xpack.security.enabled: 'false'
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - '5601:5601'
    environment:
      xpack.security.enabled: 'false'
      xpack.monitoring.ui.container.elasticsearch.enabled: 'false'
