version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      xpack.security.enabled: 'false'
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    restart: always
    ports:
      - '5601:5601'
    environment:
      xpack.security.enabled: 'false'
      xpack.monitoring.ui.container.elasticsearch.enabled: 'false'
  proxy:
    build: proxy
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./www:/var/www
  happn-stats:
    build: .
    restart: always
    ports:
      - '49494:49494'
    environment:
      REPORT_INTERVAL: 1000
      FRAGMENTS_PER_INTERVAL: 5
      ELASTIC_URL: http://elasticsearch:9200
      ELASTIC_INDEX: happn-stats
      ELASTIC_TYPE: happn-stats
